Silence "unused but set" warning for release builds
Release builds are built with -Werror, but recent Clang (tested on Clang
13 on macOS 12) emits this warning and the build fails:

```
google-benchmark/src/complexity.cc:85:10: error: variable 'sigma_gn' set but not used [-Werror,-Wunused-but-set-variable]
  double sigma_gn = 0.0;
```